student_app-master/student/accounts/urls.py
from django.conf.urls import url


from . import views



app_name='accounts'


urlpatterns=[

    url(r'^login/', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/',views.UserLogoutView.as_view(), name='logout'),
    url(r'^signup/', views.UserCreateView.as_view(), name ='signup'),
    url(r'^edit/(?P<pk>\d+)/$', views.UserEditView.as_view(), name ='edit'),

]

student_app-master/student/content/urls.py
from django.conf.urls import url
app_name='content'

from .views import (SchoolView,
                             SchoolClassView,
                             StudentInfo,
                             GradesView,
                             StudentSearchView,
                             EditView,
                             DeleteView,
StudentAddView
                    )


urlpatterns = [
    url(r'^$', SchoolView.as_view(), name="all"),
    url(r'^class/(?P<school_class_id>(\d)+)', SchoolClassView.as_view(),
        name="school-class" ),
    url(r'^student/(?P<student_id>(\d)+)', StudentInfo.as_view(),name="student"),
    url(r'^grades/(?P<student_id>(\d)+)/(?P<subject_id>(\d)+)', GradesView.as_view(), name="grades"),
    url(r'^search/', StudentSearchView.as_view(), name="search"),
    url(r'^add/', StudentAddView.as_view(), name="add"),
    url(r"edit/(?P<pk>\d+)/$",EditView.as_view(), name="edit"),
    url(r"delete/(?P<pk>\d+)/$",DeleteView.as_view(), name="delete"),

    ]

student_app-master/student/student/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^log/', views.TestPage.as_view(),name='log'),
    url(r'^thanks/', views.ThanksPage.as_view(),name='thanks'),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'content/',include('content.urls',namespace='content')),


    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student_app-master/student/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

   <link rel="stylesheet" href="{% static 'student/css/style.css' %}" type="text/css">


</head>
<body>


      <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">StudentPage </a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                             <li><a href ="{% url 'content:search'  %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                 Search student</a></li>

                            <li><a href="{% url 'content:all' %}" class="btn btn-simple">Groups</a></li>
                            <li><a href="{% url 'content:add' %}" class="btn btn-simple">Add student</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'content:all' %}" class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>


    			</div>
      </nav>
<div class="container ">
          {% block content %}

          {% endblock %}
</div>
<canvas id="canvas"></canvas>



</body>
</html>

student_app-master/student/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome <b>{{user.username}}<b> </h1>
{% endblock %}

student_app-master/student/templates/test.html
{% extends "base.html" %}

{% block content %}
<h1>
    You are now logged in ! :)<br>
          <strong>@{{user.username}}</strong>
</h1>

{% endblock %}

student_app-master/student/templates/thanks.html
{% extends "base.html" %}

{% block content %}
<h1>
    Thanks for visiting our app! See you soon .
</h1>

{% endblock %}